---

- name: "Create {{ home_path }}/app"
  file: path={{ home_path }}/app state=directory owner=pi

- name: "Create {{ home_path }}/data"
  file: path={{ home_path }}/data state=directory owner=pi

- name: "Extract backend-shadow-{{ version }}.zip into {{ home_path }}/app"
  unarchive:
    src: "../backend/build/distributions/backend-shadow-{{ version }}.zip"
    dest: "{{ home_path }}/app"
    mode: "u+x"
    owner: pi

- name: "Register co2-monitor-backend service"
  template:
    src: co2-monitor-backend.service.j2
    dest: /lib/systemd/system/co2-monitor-backend.service

- name: "Enable and restart co2-monitor-backend service"
  service: name=co2-monitor-backend daemon_reload=yes state=restarted enabled=yes
